import { StyleSheet, Platform, Dimensions } from 'react-native';
import { ThemeCouleurs } from '../../contexts/ThemeContext';
import { espacements, rayons } from '../../constantes/theme';

const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get('window');

const createStyles = (couleurs: ThemeCouleurs) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: couleurs.fond,
  },
  content: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 100,
  },
  // StoryCreator en arriere-plan (fixe, visible quand contenu principal glisse)
  storyCreatorBackground: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 1,
  },
  // Contenu principal qui glisse a droite pour reveler StoryCreator
  mainContentSlide: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 10,
    backgroundColor: couleurs.fond,
  },

  // PagerView styles
  pagerView: {
    flex: 1,
  },
  pageContainer: {
    flex: 1,
  },

  // Header
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: espacements.lg,
    paddingVertical: espacements.md,
    gap: espacements.md,
  },
  searchContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: couleurs.fondSecondaire,
    borderRadius: rayons.lg,
    paddingHorizontal: espacements.sm + 2,
    paddingVertical: espacements.xs + 2,
    gap: espacements.xs,
  },
  searchPlaceholder: {
    flex: 1,
    fontSize: 13,
    color: couleurs.texteMuted,
  },
  notifButton: {
    width: 44,
    height: 44,
    borderRadius: rayons.md,
    backgroundColor: couleurs.fondSecondaire,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  notifBadge: {
    position: 'absolute',
    top: 4,
    right: 4,
    backgroundColor: '#EF4444',
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
    borderWidth: 2,
    borderColor: couleurs.fond,
  },
  notifBadgeText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  notifBadgeDemandes: {
    backgroundColor: couleurs.primaire,
  },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: rayons.full,
    backgroundColor: couleurs.primaire,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  avatarImage: {
    width: 44,
    height: 44,
    borderRadius: 22,
  },
  avatarTexte: {
    fontSize: 16,
    fontWeight: '700',
    color: couleurs.blanc,
  },

  // Navigation avec indicateur anime
  navigation: {
    borderBottomWidth: 1,
    borderBottomColor: couleurs.bordure,
    paddingHorizontal: espacements.lg,
  },
  navContent: {
    flexDirection: 'row',
    position: 'relative',
  },
  navIndicator: {
    position: 'absolute',
    bottom: 0,
    height: 3,
    backgroundColor: couleurs.primaire,
    borderRadius: 2,
  },
  navTab: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: espacements.md,
    position: 'relative',
  },
  navTabText: {
    fontSize: 11,
    fontWeight: '600',
    color: couleurs.texteSecondaire,
    marginTop: 2,
  },
  navTabTextActive: {
    color: couleurs.primaire,
    fontWeight: '700',
  },
  navBadge: {
    backgroundColor: couleurs.erreur,
    borderRadius: 10,
    minWidth: 18,
    height: 18,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: espacements.xs,
  },
  navBadgeText: {
    fontSize: 10,
    fontWeight: '700',
    color: couleurs.blanc,
  },
  navBadgeDemandes: {
    backgroundColor: couleurs.primaire,
  },

  // Stories
  storiesSection: {
    paddingVertical: espacements.md,
  },
  storiesScroll: {
    paddingHorizontal: espacements.lg,
    gap: espacements.md,
  },
  storyItem: {
    alignItems: 'center',
    width: 70,
  },
  storyItemAdd: {
    alignItems: 'center',
    width: 70,
  },
  storyAddIcon: {
    width: 64,
    height: 64,
    borderRadius: 32,
    borderWidth: 2,
    borderColor: couleurs.primaire,
    borderStyle: 'dashed',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: espacements.xs,
  },
  storyRing: {
    width: 64,
    height: 64,
    borderRadius: 32,
    padding: 2,
    borderWidth: 2,
    borderColor: couleurs.bordure,
    marginBottom: espacements.xs,
  },
  storyRingActive: {
    borderColor: couleurs.primaire,
  },
  storyAvatar: {
    width: '100%',
    height: '100%',
    borderRadius: 30,
  },
  storyNom: {
    fontSize: 11,
    color: couleurs.texteSecondaire,
    textAlign: 'center',
  },

  // Section
  section: {
    paddingHorizontal: espacements.lg,
    marginBottom: espacements.xl,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: espacements.lg,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: couleurs.texte,
  },
  sectionSubtitle: {
    fontSize: 13,
    color: couleurs.texteSecondaire,
    marginTop: espacements.xs,
  },
  sectionAction: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: espacements.xs,
  },
  sectionActionText: {
    fontSize: 13,
    color: couleurs.texteSecondaire,
  },


  // Post
  postCard: {
    backgroundColor: couleurs.fondSecondaire,
    borderRadius: rayons.lg,
    marginBottom: espacements.md,
    borderWidth: 1,
    borderColor: couleurs.bordure,
    overflow: 'hidden',
  },
  postHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: espacements.md,
    gap: espacements.md,
  },
  postAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    marginRight: espacements.md,
  },
  postAuteurContainer: {
    flex: 1,
  },
  postAuteurRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: espacements.xs,
    flexWrap: 'wrap',
  },
  postAuteur: {
    fontSize: 14,
    fontWeight: '600',
    color: couleurs.texte,
  },
  verifiedBadge: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: couleurs.primaire,
    alignItems: 'center',
    justifyContent: 'center',
  },
  startupBadge: {
    backgroundColor: 'rgba(99, 102, 241, 0.1)',
    paddingHorizontal: espacements.sm,
    paddingVertical: 2,
    borderRadius: rayons.sm,
  },
  startupBadgeText: {
    fontSize: 10,
    fontWeight: '600',
    color: couleurs.primaire,
  },
  adminBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#dc2626',
    paddingHorizontal: espacements.sm,
    paddingVertical: 2,
    borderRadius: rayons.sm,
    gap: 4,
  },
  adminBadgeText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#fff',
  },
  adminBadgeSmall: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#dc2626',
    paddingHorizontal: 4,
    paddingVertical: 1,
    borderRadius: rayons.xs,
    gap: 2,
    marginLeft: 4,
  },
  adminBadgeSmallText: {
    fontSize: 8,
    fontWeight: '700',
    color: '#fff',
  },
  statutBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#10B981',
    paddingHorizontal: espacements.sm,
    paddingVertical: 2,
    borderRadius: rayons.sm,
    gap: 4,
  },
  statutBadgeEntrepreneur: {
    backgroundColor: '#F59E0B',
  },
  statutBadgeText: {
    fontSize: 10,
    fontWeight: '600',
    color: '#fff',
  },
  statutBadgeSmall: {
    backgroundColor: '#10B981',
    paddingHorizontal: 4,
    paddingVertical: 1,
    borderRadius: rayons.xs,
    marginLeft: 4,
  },
  statutBadgeSmallEntrepreneur: {
    backgroundColor: '#F59E0B',
  },
  statutBadgeSmallText: {
    fontSize: 8,
    fontWeight: '600',
    color: '#fff',
  },
  commentAuteurRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  postTimestamp: {
    fontSize: 12,
    color: couleurs.texteSecondaire,
    marginTop: 2,
  },
  postMore: {
    padding: espacements.sm,
  },
  postContenu: {
    fontSize: 14,
    color: couleurs.texte,
    lineHeight: 20,
    paddingHorizontal: espacements.md,
    marginBottom: espacements.md,
  },
  postMediaContainer: {
    position: 'relative',
    width: '100%',
    backgroundColor: couleurs.fondTertiaire,
  },
  postImage: {
    width: '100%',
    height: 280,
    minHeight: 200,
    maxHeight: 400,
  },
  postVideoOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.3)',
  },
  postVideoPlayBtn: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: 'rgba(0,0,0,0.6)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  // ========== LECTEUR VIDEO - Style Instagram/LinkedIn ==========
  videoModalContainer: {
    flex: 1,
    backgroundColor: '#000',
  },
  videoTouchArea: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
  },
  videoPlayer: {
    width: SCREEN_WIDTH,
    height: '100%',
  },
  videoGradientTop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 120,
  },
  videoGradientBottom: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: Platform.OS === 'ios' ? 160 : 200, // Android: plus haut pour couvrir les controles
  },
  videoCloseContainer: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 54 : 44,
    left: 16,
    zIndex: 10,
  },
  videoCloseBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(0,0,0,0.4)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  videoCenterControl: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
  },
  videoCenterBtn: {
    padding: 8,
  },
  videoCenterBtnInner: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: 'rgba(0,0,0,0.5)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.3)',
  },
  videoBottomControls: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    paddingHorizontal: 16,
    paddingBottom: Platform.OS === 'ios' ? 44 : 72, // Android: espace pour barre de navigation systeme
  },
  videoProgressBar: {
    height: 24,
    justifyContent: 'center',
    marginBottom: 8,
  },
  videoProgressTrack: {
    height: 3,
    backgroundColor: 'rgba(255,255,255,0.3)',
    borderRadius: 1.5,
    overflow: 'hidden',
  },
  videoProgressFill: {
    height: '100%',
    backgroundColor: couleurs.primaire,
    borderRadius: 1.5,
  },
  videoControlsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  videoTimeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  videoTimeText: {
    fontSize: 13,
    color: couleurs.blanc,
    fontWeight: '500',
    fontVariant: ['tabular-nums'],
  },
  videoTimeSeparator: {
    color: 'rgba(255,255,255,0.5)',
    marginHorizontal: 2,
  },
  videoRightControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  videoSmallBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  videoDurationBadge: {
    position: 'absolute',
    bottom: 8,
    right: 8,
    backgroundColor: 'rgba(0,0,0,0.7)',
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 4,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  // ========== VISIONNEUSE IMAGE - Style Instagram ==========
  imageModalContainer: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.95)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  imageModalBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  imageModalImage: {
    width: SCREEN_WIDTH,
    height: SCREEN_HEIGHT * 0.8,
  },
  imageModalCloseBtn: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 54 : 44,
    left: 16,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(0,0,0,0.4)',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
  },
  postStats: {
    flexDirection: 'row',
    paddingHorizontal: espacements.md,
    paddingVertical: espacements.sm,
    gap: espacements.lg,
    borderTopWidth: 1,
    borderTopColor: couleurs.bordure,
  },
  postStatText: {
    fontSize: 12,
    color: couleurs.texteSecondaire,
  },
  postActions: {
    flexDirection: 'row',
    borderTopWidth: 1,
    borderTopColor: couleurs.bordure,
  },
  postAction: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: espacements.md,
    gap: espacements.xs,
  },
  postActionText: {
    fontSize: 13,
    fontWeight: '500',
    color: couleurs.texteSecondaire,
  },

  // Comments Section
  commentsSection: {
    borderTopWidth: 1,
    borderTopColor: couleurs.bordure,
    padding: espacements.md,
  },
  commentInputContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: espacements.sm,
    marginBottom: espacements.md,
  },
  commentInputAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: couleurs.primaire,
    alignItems: 'center',
    justifyContent: 'center',
  },
  commentInputAvatarText: {
    fontSize: 12,
    fontWeight: '600',
    color: couleurs.blanc,
  },
  commentInput: {
    flex: 1,
    backgroundColor: couleurs.fondTertiaire,
    borderRadius: rayons.lg,
    paddingHorizontal: espacements.md,
    paddingVertical: espacements.sm,
    fontSize: 14,
    color: couleurs.texte,
    maxHeight: 100,
  },
  commentSendBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(99, 102, 241, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  commentSendBtnDisabled: {
    backgroundColor: couleurs.fondTertiaire,
  },
  commentItem: {
    flexDirection: 'row',
    gap: espacements.sm,
    marginBottom: espacements.md,
  },
  commentAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
  },
  commentContent: {
    flex: 1,
  },
  commentBubble: {
    backgroundColor: couleurs.fondTertiaire,
    borderRadius: rayons.lg,
    padding: espacements.sm,
    paddingHorizontal: espacements.md,
  },
  commentAuteur: {
    fontSize: 13,
    fontWeight: '600',
    color: couleurs.texte,
    marginBottom: 2,
  },
  commentTexte: {
    fontSize: 13,
    color: couleurs.texte,
    lineHeight: 18,
  },
  commentMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: espacements.md,
    marginTop: espacements.xs,
    paddingHorizontal: espacements.sm,
  },
  commentTime: {
    fontSize: 11,
    color: couleurs.texteSecondaire,
  },
  commentLikeBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  commentLikeText: {
    fontSize: 11,
    color: couleurs.texteSecondaire,
  },
  commentReplyBtn: {
    paddingVertical: 2,
  },
  commentReplyText: {
    fontSize: 11,
    color: couleurs.texteSecondaire,
    fontWeight: '600',
  },
  noComments: {
    alignItems: 'center',
    paddingVertical: espacements.lg,
    gap: espacements.sm,
  },
  noCommentsText: {
    fontSize: 13,
    color: couleurs.texteSecondaire,
  },
  commentBubbleHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  commentActionsMenu: {
    flexDirection: 'row',
    gap: 8,
  },
  commentActionBtn: {
    padding: 4,
  },
  commentModified: {
    fontSize: 10,
    color: couleurs.texteSecondaire,
    fontStyle: 'italic',
    marginLeft: 4,
  },
  editCommentContainer: {
    flex: 1,
  },
  editCommentInput: {
    backgroundColor: couleurs.fond,
    borderWidth: 1,
    borderColor: couleurs.primaire,
    borderRadius: rayons.md,
    paddingHorizontal: espacements.md,
    paddingVertical: espacements.sm,
    fontSize: 13,
    color: couleurs.texte,
    minHeight: 60,
    textAlignVertical: 'top',
  },
  editCommentActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: espacements.sm,
    marginTop: espacements.sm,
  },
  editCancelBtn: {
    paddingHorizontal: espacements.md,
    paddingVertical: espacements.xs,
  },
  editCancelText: {
    fontSize: 12,
    color: couleurs.texteSecondaire,
  },
  editSaveBtn: {
    backgroundColor: couleurs.primaire,
    paddingHorizontal: espacements.md,
    paddingVertical: espacements.xs,
    borderRadius: rayons.sm,
  },
  editSaveBtnDisabled: {
    opacity: 0.5,
  },
  editSaveText: {
    fontSize: 12,
    color: couleurs.blanc,
    fontWeight: '600',
  },

  // Notification banner
  notificationBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: espacements.md,
    paddingVertical: espacements.sm,
    borderRadius: rayons.md,
    marginBottom: espacements.sm,
    gap: espacements.sm,
  },
  notificationSucces: {
    backgroundColor: 'rgba(16, 185, 129, 0.15)',
    borderWidth: 1,
    borderColor: 'rgba(16, 185, 129, 0.3)',
  },
  notificationErreur: {
    backgroundColor: 'rgba(239, 68, 68, 0.15)',
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.3)',
  },
  notificationText: {
    fontSize: 13,
    fontWeight: '500',
    flex: 1,
  },
  notificationTextSucces: {
    color: '#10b981',
  },
  notificationTextErreur: {
    color: '#ef4444',
  },

  // Edit post
  editPostContainer: {
    marginBottom: espacements.md,
  },
  editPostInput: {
    backgroundColor: couleurs.fond,
    borderWidth: 1,
    borderColor: couleurs.primaire,
    borderRadius: rayons.md,
    paddingHorizontal: espacements.md,
    paddingVertical: espacements.md,
    fontSize: 14,
    color: couleurs.texte,
    minHeight: 100,
    textAlignVertical: 'top',
  },
  editPostActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: espacements.sm,
    marginTop: espacements.sm,
  },

  // Comment input avatar image
  commentInputAvatarImage: {
    width: 32,
    height: 32,
    borderRadius: 16,
  },

  // Hero
  heroSection: {
    paddingHorizontal: espacements.lg,
    marginBottom: espacements.lg,
  },
  heroCard: {
    borderRadius: rayons.xl,
    padding: espacements.xl,
  },
  heroBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: espacements.xs,
    backgroundColor: 'rgba(16, 185, 129, 0.1)',
    alignSelf: 'flex-start',
    paddingHorizontal: espacements.md,
    paddingVertical: espacements.xs,
    borderRadius: rayons.full,
    marginBottom: espacements.md,
  },
  heroBadgeText: {
    fontSize: 12,
    fontWeight: '600',
    color: couleurs.secondaire,
  },
  heroTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: couleurs.blanc,
    marginBottom: espacements.sm,
  },
  heroSubtitle: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.7)',
    lineHeight: 20,
    marginBottom: espacements.lg,
  },
  heroStats: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.1)',
    paddingTop: espacements.lg,
  },
  heroStat: {
    alignItems: 'center',
  },
  heroStatValue: {
    fontSize: 20,
    fontWeight: '700',
    color: couleurs.blanc,
  },
  heroStatLabel: {
    fontSize: 11,
    color: 'rgba(255, 255, 255, 0.6)',
    marginTop: espacements.xs,
  },
  heroStatDivider: {
    width: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
  },

  // ========== DECOUVRIR SUB-TABS ==========
  decouvrirSubTabs: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    paddingHorizontal: espacements.sm,
  },
  decouvrirSubTab: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: espacements.xs,
    paddingVertical: espacements.md,
  },
  decouvrirSubTabText: {
    fontSize: 13,
    fontWeight: '500',
  },

  // ========== DECOUVRIR REFONTE ==========
  decouvrirSearchSection: {
    paddingHorizontal: espacements.lg,
    paddingTop: espacements.sm,
    paddingBottom: espacements.xs,
  },
  decouvrirSearchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: couleurs.fondCard,
    borderRadius: rayons.md,
    borderWidth: 1,
    borderColor: couleurs.bordure,
    paddingHorizontal: 14,
    height: 44,
    gap: 10,
  },
  decouvrirSearchInput: {
    flex: 1,
    fontSize: 14,
    color: couleurs.texte,
    paddingVertical: 0,
  },
  decouvrirCategoriesScroll: {
    maxHeight: 50,
  },
  decouvrirCategoriesContainer: {
    paddingHorizontal: espacements.lg,
    paddingVertical: espacements.sm,
    gap: 8,
  },
  decouvrirCategorieChip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    gap: 6,
  },
  decouvrirCategorieText: {
    fontSize: 13,
    fontWeight: '500' as const,
  },
  decouvrirSection: {
    paddingHorizontal: espacements.lg,
    paddingTop: espacements.md,
  },
  decouvrirSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: espacements.md,
  },
  decouvrirSectionTitle: {
    fontSize: 17,
    fontWeight: '700' as const,
    color: couleurs.texte,
    flex: 1,
  },
  decouvrirSectionCount: {
    fontSize: 13,
    color: couleurs.texteMuted,
    fontWeight: '500' as const,
  },
  // Trending cards
  decouvrirTrendingScroll: {
    gap: 12,
    paddingBottom: espacements.sm,
  },
  decouvrirTrendingCard: {
    width: SCREEN_WIDTH * 0.52,
    height: 180,
    borderRadius: rayons.lg,
    overflow: 'hidden',
    position: 'relative' as const,
  },
  decouvrirTrendingImage: {
    width: '100%',
    height: '100%',
  },
  decouvrirTrendingImagePlaceholder: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  decouvrirTrendingOverlay: {
    position: 'absolute' as const,
    bottom: 0,
    left: 0,
    right: 0,
    padding: 12,
    paddingTop: 40,
  },
  decouvrirTrendingRankBadge: {
    position: 'absolute' as const,
    top: -28,
    left: 12,
    backgroundColor: '#F59E0B',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 10,
  },
  decouvrirTrendingRankText: {
    color: '#FFF',
    fontSize: 11,
    fontWeight: '800' as const,
  },
  decouvrirTrendingNom: {
    color: '#FFF',
    fontSize: 15,
    fontWeight: '700' as const,
    marginBottom: 2,
  },
  decouvrirTrendingPitch: {
    color: 'rgba(255,255,255,0.7)',
    fontSize: 11,
    marginBottom: 8,
  },
  decouvrirTrendingMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  decouvrirMaturiteBadge: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8,
  },
  decouvrirMaturiteText: {
    fontSize: 10,
    fontWeight: '600' as const,
  },
  decouvrirTrendingStat: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
  },
  decouvrirTrendingStatText: {
    color: 'rgba(255,255,255,0.7)',
    fontSize: 11,
  },
  // Empty state decouvrir
  decouvrirEmptyState: {
    alignItems: 'center',
    paddingVertical: espacements.xxl,
    paddingHorizontal: espacements.lg,
  },
  decouvrirEmptyIcon: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: couleurs.primaire + '15',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: espacements.md,
  },
  decouvrirEmptyTitle: {
    fontSize: 16,
    fontWeight: '600' as const,
    color: couleurs.texte,
    marginBottom: espacements.xs,
    textAlign: 'center',
  },
  decouvrirEmptySubtitle: {
    fontSize: 14,
    color: couleurs.texteSecondaire,
    textAlign: 'center',
    lineHeight: 20,
  },
  decouvrirEmptyBtn: {
    marginTop: espacements.md,
    backgroundColor: couleurs.primaire,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 20,
  },
  decouvrirEmptyBtnText: {
    color: '#FFF',
    fontSize: 14,
    fontWeight: '600' as const,
  },

  // Startup Card
  startupCard: {
    backgroundColor: couleurs.fondSecondaire,
    borderRadius: rayons.lg,
    marginBottom: espacements.md,
    borderWidth: 1,
    borderColor: couleurs.bordure,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 2,
  },
  startupImage: {
    width: '100%',
    height: 140,
  },
  startupContent: {
    padding: espacements.md,
  },
  startupHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: espacements.xs,
  },
  startupLogo: {
    width: 36,
    height: 36,
    borderRadius: rayons.sm,
    marginLeft: espacements.sm,
    borderWidth: 1,
    borderColor: couleurs.bordure,
  },
  startupNom: {
    fontSize: 15,
    fontWeight: '700',
    color: couleurs.texte,
  },
  startupLocation: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: espacements.xs,
    marginTop: 2,
  },
  startupVille: {
    fontSize: 12,
    color: couleurs.texteSecondaire,
  },
  startupDescription: {
    fontSize: 13,
    color: couleurs.texteSecondaire,
    lineHeight: 18,
    marginBottom: espacements.sm,
  },
  startupTags: {
    flexDirection: 'row',
    gap: espacements.xs,
    marginBottom: espacements.sm,
    flexWrap: 'wrap',
  },
  startupTag: {
    backgroundColor: couleurs.fondTertiaire,
    paddingHorizontal: espacements.sm,
    paddingVertical: 3,
    borderRadius: rayons.full || 50,
  },
  startupTagText: {
    fontSize: 11,
    color: couleurs.texteSecondaire,
    fontWeight: '500',
  },
  startupStats: {
    flexDirection: 'row',
    gap: espacements.md,
    marginBottom: espacements.sm,
    paddingBottom: espacements.sm,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: couleurs.bordure,
  },
  startupStat: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: espacements.xs,
  },
  startupStatText: {
    fontSize: 12,
    color: couleurs.texteSecondaire,
  },
  startupActions: {
    flexDirection: 'row',
    gap: espacements.sm,
  },
  startupBtnPrimary: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: couleurs.primaire,
    paddingVertical: 10,
    borderRadius: rayons.md,
    gap: espacements.xs,
  },
  startupBtnSuivi: {
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: couleurs.primaire,
  },
  startupBtnPrimaryText: {
    fontSize: 13,
    fontWeight: '600',
    color: couleurs.blanc,
  },
  startupBtnSuiviText: {
    color: couleurs.primaire,
  },
  startupBtnSecondary: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: couleurs.bordure,
    borderRadius: rayons.md,
  },

  // ============ LIVE TAB ============
  liveContainer: {
    paddingHorizontal: espacements.lg,
    paddingTop: espacements.lg,
    marginBottom: espacements.xl,
  },
  liveHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: espacements.md,
  },
  liveHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: espacements.sm,
  },
  liveCountBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: couleurs.erreur,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 12,
    gap: 4,
  },
  liveCountDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: couleurs.blanc,
  },
  liveCountText: {
    color: couleurs.blanc,
    fontSize: 11,
    fontWeight: '700' as const,
  },
  goLiveBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 16,
    paddingVertical: 9,
    borderRadius: 20,
    backgroundColor: couleurs.erreur,
  },
  goLiveBtnText: {
    color: couleurs.blanc,
    fontSize: 13,
    fontWeight: '700' as const,
  },
  // Section pattern (matches decouvrir)
  liveSection: {
    paddingTop: espacements.md,
  },
  liveSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: espacements.md,
  },
  liveSectionTitle: {
    fontSize: 17,
    fontWeight: '700' as const,
    color: couleurs.texte,
    flex: 1,
  },
  liveSectionCount: {
    fontSize: 13,
    color: couleurs.texteMuted,
    fontWeight: '500' as const,
  },
  liveDivider: {
    height: 1,
    backgroundColor: couleurs.bordure,
    marginVertical: espacements.sm,
  },
  // Horizontal scroll (matches decouvrir trending)
  liveTrendingScroll: {
    gap: 12,
    paddingBottom: espacements.sm,
  },
  // Search bar
  liveSearchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: couleurs.fondSecondaire,
    borderRadius: rayons.lg,
    paddingHorizontal: espacements.md,
    paddingVertical: espacements.sm,
    borderWidth: 1,
    borderColor: couleurs.bordure,
    gap: espacements.sm,
  },
  liveSearchInput: {
    flex: 1,
    fontSize: 14,
    color: couleurs.texte,
    paddingVertical: 4,
  },
  // Sort chips
  liveSortRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: espacements.sm,
  },
  liveSortChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    backgroundColor: couleurs.fondSecondaire,
    borderWidth: 1,
    borderColor: couleurs.bordure,
  },
  liveSortChipActive: {
    backgroundColor: couleurs.primaire,
    borderColor: couleurs.primaire,
  },
  liveSortChipText: {
    fontSize: 12,
    fontWeight: '600' as const,
    color: couleurs.texteSecondaire,
  },
  liveSortChipTextActive: {
    color: couleurs.blanc,
  },
  liveStatsCompact: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginLeft: 'auto' as const,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 10,
    backgroundColor: couleurs.fondSecondaire,
  },
  liveStatsCompactText: {
    fontSize: 11,
    fontWeight: '600' as const,
    color: couleurs.texteSecondaire,
  },
  // No results
  liveNoResults: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: espacements.xxl,
    gap: espacements.md,
  },
  liveNoResultsText: {
    fontSize: 14,
    color: couleurs.texteSecondaire,
    textAlign: 'center' as const,
  },
  // Active lives container
  livesActiveContainer: {
    gap: espacements.md,
  },
  // Empty state
  liveEmptyState: {
    gap: espacements.lg,
  },
  liveEmptyHero: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 40,
    paddingHorizontal: espacements.xl,
    gap: espacements.md,
    borderRadius: rayons.xl,
  },
  liveEmptyIconRing: {
    width: 72,
    height: 72,
    borderRadius: 36,
    borderWidth: 2,
    borderColor: `${couleurs.primaireLight}40`,
    backgroundColor: `${couleurs.primaireLight}15`,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: espacements.xs,
  },
  liveEmptyTitle: {
    fontSize: 20,
    fontWeight: '700' as const,
    color: couleurs.blanc,
    textAlign: 'center' as const,
  },
  liveEmptySubtitle: {
    fontSize: 14,
    color: `${couleurs.blanc}99`,
    textAlign: 'center' as const,
    lineHeight: 20,
  },
  liveEmptyCTABtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 28,
    paddingVertical: 13,
    borderRadius: 24,
    backgroundColor: couleurs.erreur,
    marginTop: espacements.sm,
  },
  liveEmptyCTAText: {
    color: couleurs.blanc,
    fontSize: 15,
    fontWeight: '700' as const,
  },
  // How-to section
  liveHowToSection: {
    gap: espacements.md,
  },
  liveHowToSteps: {
    flexDirection: 'row',
    gap: espacements.sm,
  },
  liveHowToStep: {
    flex: 1,
    alignItems: 'center',
    backgroundColor: couleurs.fondSecondaire,
    borderRadius: rayons.lg,
    paddingVertical: espacements.md,
    paddingHorizontal: espacements.sm,
    borderWidth: 1,
    borderColor: couleurs.bordure,
    gap: 6,
  },
  liveHowToStepNum: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  liveHowToStepNumText: {
    fontSize: 14,
    fontWeight: '700' as const,
  },
  liveHowToStepTitle: {
    fontSize: 12,
    fontWeight: '600' as const,
    color: couleurs.texte,
  },
  liveHowToStepDesc: {
    fontSize: 10,
    color: couleurs.texteSecondaire,
    textAlign: 'center' as const,
  },

  // Messages
  messagesCard: {
    backgroundColor: couleurs.fondSecondaire,
    borderRadius: rayons.lg,
    borderWidth: 1,
    borderColor: couleurs.bordure,
    overflow: 'hidden',
  },
  messagesHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: espacements.lg,
    borderBottomWidth: 1,
    borderBottomColor: couleurs.bordure,
  },
  messagesHeaderTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: couleurs.texte,
  },
  messagesNewBtn: {
    width: 36,
    height: 36,
    borderRadius: rayons.md,
    backgroundColor: 'rgba(99, 102, 241, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  messagesList: {
    padding: espacements.sm,
  },
  messageRow: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: espacements.md,
    borderRadius: rayons.md,
  },
  messageRowUnread: {
    backgroundColor: 'rgba(99, 102, 241, 0.05)',
  },
  messageAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    marginRight: espacements.md,
  },
  messageContent: {
    flex: 1,
  },
  messageExpediteur: {
    fontSize: 14,
    color: couleurs.texte,
  },
  messageExpediteurUnread: {
    fontWeight: '600',
  },
  messageDernier: {
    fontSize: 13,
    color: couleurs.texteSecondaire,
    marginTop: 2,
  },
  messageMeta: {
    alignItems: 'flex-end',
  },
  messageDate: {
    fontSize: 11,
    color: couleurs.texteSecondaire,
  },
  messageUnreadDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: couleurs.primaire,
    marginTop: espacements.xs,
  },
  messageUnreadBadge: {
    backgroundColor: couleurs.primaire,
    borderRadius: 10,
    minWidth: 20,
    height: 20,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 6,
    marginTop: espacements.xs,
  },
  messageUnreadBadgeText: {
    fontSize: 11,
    fontWeight: '600',
    color: couleurs.blanc,
  },
  messagesSearchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: couleurs.fondTertiaire,
    borderRadius: rayons.md,
    paddingHorizontal: espacements.md,
    paddingVertical: espacements.sm,
    marginHorizontal: espacements.md,
    marginBottom: espacements.sm,
    gap: espacements.sm,
  },
  messagesSearchInput: {
    flex: 1,
    fontSize: 14,
    color: couleurs.texte,
    padding: 0,
  },
  emptyMessages: {
    alignItems: 'center',
    paddingVertical: espacements.xxl,
    gap: espacements.md,
  },
  emptyMessagesText: {
    fontSize: 14,
    color: couleurs.texteSecondaire,
  },
  messagesEmptyText: {
    fontSize: 14,
    color: couleurs.texteSecondaire,
    textAlign: 'center',
    paddingVertical: espacements.lg,
  },
  chargementText: {
    fontSize: 14,
    color: couleurs.texteSecondaire,
    textAlign: 'center',
    paddingVertical: espacements.lg,
  },
  startConversationBtn: {
    backgroundColor: couleurs.primaire,
    paddingHorizontal: espacements.lg,
    paddingVertical: espacements.sm,
    borderRadius: rayons.md,
  },
  startConversationBtnText: {
    fontSize: 14,
    fontWeight: '600',
    color: couleurs.blanc,
  },
  conversationHeaderInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: espacements.sm,
    flex: 1,
    justifyContent: 'center',
  },
  conversationHeaderAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
  },
  messagesConversation: {
    flex: 1,
    maxHeight: 400,
  },
  messageBubble: {
    maxWidth: '80%',
    padding: espacements.md,
    borderRadius: rayons.lg,
    marginBottom: espacements.sm,
    marginHorizontal: espacements.md,
  },
  messageBubbleMoi: {
    alignSelf: 'flex-end',
    backgroundColor: couleurs.primaire,
    borderBottomRightRadius: 4,
  },
  messageBubbleAutre: {
    alignSelf: 'flex-start',
    backgroundColor: couleurs.fondTertiaire,
    borderBottomLeftRadius: 4,
  },
  messageBubbleText: {
    fontSize: 14,
    color: couleurs.texte,
    lineHeight: 20,
  },
  messageBubbleTextMoi: {
    color: couleurs.blanc,
  },
  messageBubbleTime: {
    fontSize: 10,
    color: couleurs.texteSecondaire,
    marginTop: espacements.xs,
    alignSelf: 'flex-end',
  },
  messageBubbleTimeMoi: {
    color: 'rgba(255, 255, 255, 0.7)',
  },
  messageInputContainer: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    padding: espacements.md,
    borderTopWidth: 1,
    borderTopColor: couleurs.bordure,
    gap: espacements.sm,
  },
  messageInput: {
    flex: 1,
    backgroundColor: couleurs.fondTertiaire,
    borderRadius: rayons.lg,
    paddingHorizontal: espacements.md,
    paddingVertical: espacements.sm,
    fontSize: 14,
    color: couleurs.texte,
    maxHeight: 100,
  },
  sendButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: couleurs.primaire,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sendButtonDisabled: {
    backgroundColor: couleurs.fondTertiaire,
  },
  modalSearchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: couleurs.fondTertiaire,
    borderRadius: rayons.md,
    paddingHorizontal: espacements.md,
    paddingVertical: espacements.sm,
    marginBottom: espacements.md,
    gap: espacements.sm,
  },
  modalSearchInput: {
    flex: 1,
    fontSize: 14,
    color: couleurs.texte,
    padding: 0,
  },
  searchResults: {
    maxHeight: 300,
  },
  searchResultItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: espacements.md,
    borderBottomWidth: 1,
    borderBottomColor: couleurs.bordure,
    gap: espacements.md,
  },
  searchResultAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
  },
  searchResultName: {
    fontSize: 14,
    fontWeight: '500',
    color: couleurs.texte,
  },
  noResultsText: {
    fontSize: 14,
    color: couleurs.texteSecondaire,
    textAlign: 'center',
    paddingVertical: espacements.lg,
  },
  selectedDestinataireContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: couleurs.fondTertiaire,
    borderRadius: rayons.md,
    padding: espacements.md,
    marginBottom: espacements.md,
    gap: espacements.sm,
  },
  selectedDestinataireAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
  },
  selectedDestinataireName: {
    flex: 1,
    fontSize: 14,
    fontWeight: '500',
    color: couleurs.texte,
  },
  modalMessageInput: {
    backgroundColor: couleurs.fondTertiaire,
    borderRadius: rayons.md,
    padding: espacements.md,
    fontSize: 14,
    color: couleurs.texte,
    minHeight: 100,
    textAlignVertical: 'top',
    marginBottom: espacements.md,
  },
  sendMessageBtn: {
    backgroundColor: couleurs.primaire,
    borderRadius: rayons.md,
    paddingVertical: espacements.md,
    alignItems: 'center',
  },
  sendMessageBtnDisabled: {
    backgroundColor: couleurs.fondTertiaire,
  },
  sendMessageBtnText: {
    fontSize: 14,
    fontWeight: '600',
    color: couleurs.blanc,
  },

  // Footer
  footer: {
    alignItems: 'center',
    paddingVertical: espacements.xxl,
    paddingHorizontal: espacements.lg,
  },
  footerLogo: {
    fontSize: 24,
    fontWeight: '900',
    color: couleurs.primaire,
    marginBottom: espacements.xs,
  },
  footerText: {
    fontSize: 14,
    color: couleurs.texte,
    marginBottom: espacements.xs,
  },
  footerSubtext: {
    fontSize: 12,
    color: couleurs.texteSecondaire,
  },

  // FAB
  fab: {
    position: 'absolute',
    bottom: 30,
    right: 20,
    zIndex: 100,
  },
  fabGradientWrapper: {
    borderRadius: 28,
    shadowColor: couleurs.primaire,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  fabGradient: {
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  fabBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    zIndex: 90,
  },
  scrollTopBtn: {
    position: 'absolute',
    bottom: 100,
    right: 20,
    zIndex: 99,
  },
  scrollTopBtnInner: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: couleurs.fondSecondaire,
    borderWidth: 1,
    borderColor: couleurs.bordure,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  fabMenu: {
    position: 'absolute',
    bottom: 100,
    right: 20,
    zIndex: 95,
    alignItems: 'flex-end',
    gap: espacements.md,
  },
  fabActionContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: espacements.md,
  },
  fabAction: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  fabActionLabel: {
    backgroundColor: couleurs.fondSecondaire,
    paddingHorizontal: espacements.md,
    paddingVertical: espacements.sm,
    borderRadius: rayons.md,
    fontSize: 13,
    fontWeight: '600',
    color: couleurs.texte,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },

  // Reply styles
  replyingToBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(99, 102, 241, 0.1)',
    paddingHorizontal: espacements.md,
    paddingVertical: espacements.sm,
    borderRadius: rayons.md,
    marginBottom: espacements.md,
  },
  replyingToContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: espacements.sm,
  },
  replyingToText: {
    fontSize: 13,
    color: couleurs.texteSecondaire,
  },
  replyingToName: {
    fontWeight: '600',
    color: couleurs.primaire,
  },
  cancelReplyBtn: {
    padding: espacements.xs,
  },
  viewRepliesBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: espacements.xs,
    marginTop: espacements.sm,
    paddingHorizontal: espacements.sm,
  },
  viewRepliesText: {
    fontSize: 12,
    color: couleurs.primaire,
    fontWeight: '500',
  },
  replyItem: {
    flexDirection: 'row',
    gap: espacements.sm,
    marginLeft: 20,
    marginBottom: espacements.sm,
    paddingLeft: espacements.md,
  },
  replyLine: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 16,
    width: 2,
    backgroundColor: couleurs.bordure,
    borderRadius: 1,
  },
  replyAvatar: {
    width: 28,
    height: 28,
    borderRadius: 14,
  },
  replyBubble: {
    backgroundColor: 'rgba(99, 102, 241, 0.05)',
    borderRadius: rayons.lg,
    padding: espacements.sm,
    paddingHorizontal: espacements.md,
    borderLeftWidth: 2,
    borderLeftColor: couleurs.primaire,
  },

  // Loading & Empty states
  loadingContainer: {
    padding: espacements.xxl,
    alignItems: 'center',
  },
  loadingText: {
    fontSize: 14,
    color: couleurs.texteSecondaire,
  },
  emptyContainer: {
    padding: espacements.xxl,
    alignItems: 'center',
    gap: espacements.md,
  },
  emptyText: {
    fontSize: 16,
    fontWeight: '600',
    color: couleurs.texte,
  },
  emptySubtext: {
    fontSize: 14,
    color: couleurs.texteSecondaire,
  },

  // Modal creer publication
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: couleurs.fond,
    borderTopLeftRadius: rayons.xl,
    borderTopRightRadius: rayons.xl,
    maxHeight: '90%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: espacements.lg,
    borderBottomWidth: 1,
    borderBottomColor: couleurs.bordure,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: couleurs.texte,
  },
  modalCloseBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: couleurs.fondSecondaire,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalBody: {
    padding: espacements.lg,
  },
  modalAuthor: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: espacements.md,
    marginBottom: espacements.lg,
  },
  modalAuthorAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: couleurs.primaire,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalAuthorAvatarImage: {
    width: 44,
    height: 44,
    borderRadius: 22,
  },
  modalAuthorAvatarText: {
    fontSize: 16,
    fontWeight: '700',
    color: couleurs.blanc,
  },
  modalAuthorName: {
    fontSize: 16,
    fontWeight: '600',
    color: couleurs.texte,
  },
  modalTextInput: {
    fontSize: 16,
    color: couleurs.texte,
    minHeight: 150,
    textAlignVertical: 'top',
    lineHeight: 24,
  },
  modalCharCount: {
    fontSize: 12,
    color: couleurs.texteSecondaire,
    textAlign: 'right',
    marginTop: espacements.sm,
  },
  // Mentions autocomplete dropdown
  mentionDropdown: {
    backgroundColor: couleurs.fondElevated,
    borderRadius: rayons.md,
    borderWidth: 1,
    borderColor: couleurs.bordure,
    maxHeight: 200,
    marginBottom: espacements.sm,
  },
  mentionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: couleurs.bordure,
  },
  mentionItemAvatar: {
    width: 32,
    height: 32,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  mentionItemAvatarImg: {
    width: 32,
    height: 32,
    borderRadius: 10,
  },
  mentionItemInfo: {
    flex: 1,
  },
  mentionItemName: {
    fontSize: 14,
    fontWeight: '600',
    color: couleurs.texte,
  },
  mentionItemSub: {
    fontSize: 11,
    color: couleurs.texteSecondaire,
  },
  modalFooter: {
    padding: espacements.lg,
    borderTopWidth: 1,
    borderTopColor: couleurs.bordure,
  },
  modalPublishBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: couleurs.primaire,
    paddingVertical: espacements.md,
    borderRadius: rayons.md,
    gap: espacements.sm,
  },
  modalPublishBtnDisabled: {
    backgroundColor: couleurs.fondTertiaire,
  },
  modalPublishBtnText: {
    fontSize: 16,
    fontWeight: '600',
    color: couleurs.blanc,
  },

  // Media Preview dans Modal
  mediaPreviewContainer: {
    position: 'relative',
    marginTop: espacements.md,
    borderRadius: rayons.md,
    overflow: 'hidden',
    backgroundColor: couleurs.fondTertiaire,
  },
  mediaPreview: {
    width: '100%',
    height: 200,
    borderRadius: rayons.md,
  },
  mediaVideoIndicator: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.3)',
  },
  mediaRemoveBtn: {
    position: 'absolute',
    top: espacements.sm,
    right: espacements.sm,
    backgroundColor: 'rgba(0,0,0,0.5)',
    borderRadius: 14,
  },

  // Multi-media preview row
  mediasPreviewRow: {
    marginTop: espacements.md,
  },
  mediaPreviewItem: {
    position: 'relative',
    width: 80,
    height: 80,
    marginRight: espacements.sm,
    borderRadius: rayons.sm,
    overflow: 'hidden',
  },
  mediaPreviewThumb: {
    width: '100%',
    height: '100%',
  },
  mediaVideoIndicatorSmall: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.3)',
  },
  mediaRemoveBtnSmall: {
    position: 'absolute',
    top: 2,
    right: 2,
    backgroundColor: 'rgba(0,0,0,0.5)',
    borderRadius: 10,
  },
  mediaIndexBadge: {
    position: 'absolute',
    bottom: 4,
    left: 4,
    backgroundColor: 'rgba(0,0,0,0.6)',
    borderRadius: rayons.xs,
    paddingHorizontal: 4,
    paddingVertical: 1,
  },
  mediaIndexText: {
    color: couleurs.blanc,
    fontSize: 10,
    fontWeight: '600',
  },
  mediasCount: {
    color: couleurs.texteSecondaire,
    fontSize: 12,
    marginTop: espacements.xs,
  },

  // Barre d'actions medias dans Modal
  modalMediaBar: {
    flexDirection: 'row',
    borderTopWidth: 1,
    borderTopColor: couleurs.bordure,
    paddingVertical: espacements.sm,
    paddingHorizontal: espacements.lg,
  },
  modalMediaBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: espacements.xs,
    paddingVertical: espacements.sm,
  },
  modalMediaBtnText: {
    fontSize: 13,
    fontWeight: '500',
    color: couleurs.primaire,
  },

  // Full Screen Search
  fullSearchContainer: {
    flex: 1,
    backgroundColor: couleurs.fond,
  },
  fullSearchHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: espacements.md,
    paddingVertical: espacements.sm,
    gap: espacements.sm,
    borderBottomWidth: 1,
    borderBottomColor: couleurs.bordure,
  },
  fullSearchInputContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: couleurs.fondSecondaire,
    borderRadius: rayons.lg,
    paddingHorizontal: espacements.sm + 2,
    paddingVertical: espacements.xs + 3,
    gap: espacements.xs,
  },
  fullSearchInput: {
    flex: 1,
    fontSize: 15,
    color: couleurs.texte,
    paddingVertical: 0,
  },
  fullSearchCancel: {
    paddingHorizontal: espacements.xs,
    paddingVertical: espacements.xs,
  },
  fullSearchCancelText: {
    fontSize: 15,
    color: couleurs.primaire,
    fontWeight: '500',
  },
  fullSearchContent: {
    flex: 1,
  },
  fullSearchHint: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: espacements.xl,
    paddingBottom: 80,
  },
  fullSearchHintIcon: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: couleurs.primaireLight,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: espacements.lg,
  },
  fullSearchHintTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: couleurs.texte,
    marginBottom: espacements.xs,
    textAlign: 'center',
  },
  fullSearchHintText: {
    fontSize: 14,
    color: couleurs.texteSecondaire,
    textAlign: 'center',
    lineHeight: 20,
  },
  fullSearchLoading: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingBottom: 80,
  },
  fullSearchLoadingDots: {
    flexDirection: 'row',
    gap: espacements.sm,
    marginBottom: espacements.md,
  },
  fullSearchDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  fullSearchLoadingText: {
    fontSize: 14,
    color: couleurs.texteSecondaire,
  },
  fullSearchEmpty: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: espacements.xl,
    paddingBottom: 80,
  },
  fullSearchEmptyIcon: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: couleurs.fondSecondaire,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: espacements.lg,
  },
  fullSearchEmptyTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: couleurs.texte,
    marginBottom: espacements.xs,
  },
  fullSearchEmptyText: {
    fontSize: 14,
    color: couleurs.texteSecondaire,
    textAlign: 'center',
  },
  fullSearchResults: {
    flex: 1,
  },
  fullSearchResultsCount: {
    fontSize: 12,
    color: couleurs.texteMuted,
    paddingHorizontal: espacements.md,
    paddingTop: espacements.sm,
    paddingBottom: espacements.xs,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  fullSearchResultItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: espacements.sm,
    paddingHorizontal: espacements.md,
    gap: espacements.sm,
  },
  fullSearchResultItemPressed: {
    backgroundColor: couleurs.fondSecondaire,
  },
  fullSearchResultInfo: {
    flex: 1,
  },
  fullSearchResultName: {
    fontSize: 15,
    fontWeight: '600',
    color: couleurs.texte,
    marginBottom: 1,
  },
  fullSearchResultSub: {
    fontSize: 12,
    color: couleurs.texteSecondaire,
  },
  fullSearchResultArrow: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: couleurs.fondSecondaire,
    alignItems: 'center',
    justifyContent: 'center',
  },

  // Historique de recherche
  historiqueHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: espacements.lg,
    paddingVertical: espacements.md,
    borderBottomWidth: 1,
    borderBottomColor: couleurs.bordure,
  },
  historiqueTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: couleurs.texteSecondaire,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  historiqueClear: {
    fontSize: 13,
    color: couleurs.primaire,
    fontWeight: '500',
  },
  historiqueItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: espacements.md,
    paddingHorizontal: espacements.lg,
    gap: espacements.md,
  },
  historiqueIconContainer: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: couleurs.fondSecondaire,
    alignItems: 'center',
    justifyContent: 'center',
  },
  historiqueText: {
    flex: 1,
    fontSize: 15,
    color: couleurs.texte,
  },
  historiqueDeleteBtn: {
    padding: espacements.xs,
  },
  // ================ STYLES ENTREPRENEUR ================
  entrepreneurContainer: {
    flex: 1,
    paddingTop: espacements.md,
  },
  entrepreneurHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: espacements.lg,
    marginBottom: espacements.lg,
  },
  entrepreneurTitle: {
    fontSize: 24,
    fontWeight: '700',
  },
  entrepreneurSubtitle: {
    fontSize: 14,
    marginTop: 2,
  },
  entrepreneurCreateBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: espacements.md,
    paddingVertical: espacements.sm,
    borderRadius: rayons.md,
    gap: 6,
  },
  entrepreneurCreateBtnText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  entrepreneurList: {
    flex: 1,
  },
  entrepreneurListContent: {
    paddingHorizontal: espacements.lg,
    paddingBottom: 100,
  },
  entrepreneurEmptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 60,
    paddingHorizontal: espacements.xl,
    borderRadius: rayons.lg,
    marginTop: espacements.xl,
  },
  entrepreneurEmptyTitle: {
    fontSize: 20,
    fontWeight: '600',
    marginTop: espacements.lg,
    textAlign: 'center',
  },
  entrepreneurEmptyText: {
    fontSize: 14,
    textAlign: 'center',
    marginTop: espacements.sm,
    lineHeight: 20,
  },
  entrepreneurEmptyBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: espacements.lg,
    paddingVertical: espacements.md,
    borderRadius: rayons.md,
    marginTop: espacements.xl,
    gap: 8,
  },
  entrepreneurEmptyBtnText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '600',
  },
  entrepreneurLoading: {
    alignItems: 'center',
    paddingVertical: 60,
  },
  entrepreneurLoadingText: {
    fontSize: 14,
  },
  entrepreneurProjectCard: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: espacements.md,
    borderRadius: rayons.lg,
    marginBottom: espacements.sm,
  },
  entrepreneurProjectImage: {
    width: 60,
    height: 60,
    borderRadius: rayons.md,
  },
  entrepreneurProjectImagePlaceholder: {
    width: 60,
    height: 60,
    borderRadius: rayons.md,
    alignItems: 'center',
    justifyContent: 'center',
  },
  entrepreneurProjectInfo: {
    flex: 1,
    marginLeft: espacements.md,
    marginRight: espacements.sm,
  },
  entrepreneurProjectHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  entrepreneurProjectName: {
    fontSize: 16,
    fontWeight: '600',
    flex: 1,
    marginRight: espacements.sm,
  },
  entrepreneurProjectStatus: {
    paddingHorizontal: espacements.sm,
    paddingVertical: 2,
    borderRadius: rayons.full,
  },
  entrepreneurStatusPublished: {
    backgroundColor: '#10B98120',
  },
  entrepreneurStatusDraft: {
    backgroundColor: '#F59E0B20',
  },
  entrepreneurProjectStatusText: {
    fontSize: 10,
    fontWeight: '600',
    color: '#6B7280',
  },
  entrepreneurProjectPitch: {
    fontSize: 13,
    lineHeight: 18,
    marginBottom: 6,
  },
  entrepreneurProjectMeta: {
    flexDirection: 'row',
    gap: espacements.md,
  },
  entrepreneurProjectMetaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  entrepreneurProjectMetaText: {
    fontSize: 12,
  },
});

export default createStyles;
