/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/accueil` | `/accueil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/choix-statut` | `/choix-statut`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/messages` | `/messages`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/notifications` | `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/profil` | `/profil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/connexion` | `/connexion`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/inscription` | `/inscription`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/amis/[id]` | `/amis/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(app)'}/conversation/[id]` | `/conversation/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(app)'}/utilisateur/[id]` | `/utilisateur/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/accueil` | `/accueil`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/choix-statut` | `/choix-statut`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/messages` | `/messages`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/notifications` | `/notifications`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/profil` | `/profil`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/connexion` | `/connexion`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/inscription` | `/inscription`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/amis/[id]` | `/amis/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `${'/(app)'}/conversation/[id]` | `/conversation/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `${'/(app)'}/utilisateur/[id]` | `/utilisateur/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/accueil${`?${string}` | `#${string}` | ''}` | `/accueil${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/choix-statut${`?${string}` | `#${string}` | ''}` | `/choix-statut${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/messages${`?${string}` | `#${string}` | ''}` | `/messages${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/notifications${`?${string}` | `#${string}` | ''}` | `/notifications${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/profil${`?${string}` | `#${string}` | ''}` | `/profil${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/connexion${`?${string}` | `#${string}` | ''}` | `/connexion${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/inscription${`?${string}` | `#${string}` | ''}` | `/inscription${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/accueil` | `/accueil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/choix-statut` | `/choix-statut`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/messages` | `/messages`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/notifications` | `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/profil` | `/profil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/connexion` | `/connexion`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/inscription` | `/inscription`; params?: Router.UnknownInputParams; } | `${'/(app)'}/amis/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/amis/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/conversation/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/conversation/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/utilisateur/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/utilisateur/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `${'/(app)'}/amis/[id]` | `/amis/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(app)'}/conversation/[id]` | `/conversation/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(app)'}/utilisateur/[id]` | `/utilisateur/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
