/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/accueil` | `/accueil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/profil` | `/profil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/connexion` | `/connexion`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/inscription` | `/inscription`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/accueil` | `/accueil`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/profil` | `/profil`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/connexion` | `/connexion`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/inscription` | `/inscription`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/accueil${`?${string}` | `#${string}` | ''}` | `/accueil${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/profil${`?${string}` | `#${string}` | ''}` | `/profil${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/connexion${`?${string}` | `#${string}` | ''}` | `/connexion${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/inscription${`?${string}` | `#${string}` | ''}` | `/inscription${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/accueil` | `/accueil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/profil` | `/profil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/connexion` | `/connexion`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/inscription` | `/inscription`; params?: Router.UnknownInputParams; };
    }
  }
}
